#!/usr/bin/env python3
"""
Turn an offline model JSON into the C table embedded in fpb_producer.c.

Run:  python3 tools/mkprofile.py captures/<date>/fpb_offline_model.json

The table is spliced between the FPB-CAPTURES-BEGIN/END sentinels so the rig
stays two dependency-free .c files -- the producer never opens this JSON, and
`cc -o fpb_producer fpb_producer.c` keeps working with no flags and no headers.

What is taken from the model, and what is not:

  TAKEN  the per-stream derived schedule (ordered work items, offsets as a
         fraction of that stream's median E_total), the ACQUIRE anchor, and
         the E_total marginal as six quantile knots plus max.

  FITTED one knot. The model's quantiles stop at p90, leaving the segment
         from there to max unshaped. A p99 knot is solved in closed form so
         the sampled mean equals the captured mean -- derived from the data,
         not picked by hand. The result is an 8-knot piecewise-linear inverse
         CDF, which needs no libm and so keeps the zero-flag build.

  ABSENT any correlation. The model is summary statistics: it has no
         per-frame arrays, so cross-milestone covariance within a frame and
         frame-to-frame autocorrelation are both unavailable. See the note
         in fpb_producer.c above fpb_cap_e_total().
"""
import json, sys, os

QS = [0.0, 0.10, 0.25, 0.50, 0.75, 0.90]
KEYS = ["min_us", "p10_us", "p25_us", "median_us", "p75_us", "p90_us"]
# The emitted CDF adds a solved p99 and max, giving knots at
#   0, .10, .25, .50, .75, .90, .99, 1.0

BEGIN = "/* FPB-CAPTURES-BEGIN"
END = "/* FPB-CAPTURES-END */"


def solve_p99(e):
    """Solve the p99 knot so the piecewise CDF reproduces the captured mean."""
    v = [e[k] for k in KEYS]
    lin = sum(0.5 * (v[i] + v[i + 1]) * (QS[i + 1] - QS[i]) for i in range(len(QS) - 1))
    x = 20.0 * (e["mean_us"] - lin - 0.045 * e["p90_us"] - 0.005 * e["max_us"])
    got = lin + 0.09 * (e["p90_us"] + x) / 2.0 + 0.01 * (x + e["max_us"]) / 2.0
    return x, got


def milestones(sc):
    """work items + the three anchors, ordered, as fractions of E_total."""
    E = sc["e_total_ns"]
    ms = [(w["e_ns"] / E, "%s.%d" % (w["id"], w["k"]), "FPB_KIND_DELTA")
          for w in sc["work_items"] if w["e_ns"] > 0.0]
    ms.append((sc["anchors"]["ACQUIRE"] / E, "ACQUIRE", "FPB_KIND_ANCHOR"))
    ms.sort(key=lambda t: t[0])
    return ([(0.0, "FRAME_OPEN", "FPB_KIND_ANCHOR")] + ms
            + [(1.0, "FRAME_END", "FPB_KIND_ANCHOR")])


def main(path, csrc="fpb_producer.c"):
    d = json.load(open(path))
    streams = [(k.split(".")[0].lower(), v) for k, v in d["streams"].items()]
    streams.append(("combined", d["combined"]))

    out, tbl, names = [], [], []
    for name, st in streams:
        ms = milestones(st["schedule"])
        e = st["profile"]["e_total"]
        p99, got = solve_p99(e)
        if not (e["p90_us"] <= p99 <= e["max_us"]):
            sys.exit("%s: solved p99 %.0f outside [p90 %.0f, max %.0f]"
                     % (name, p99, e["p90_us"], e["max_us"]))
        if abs(got - e["mean_us"]) > 1.0:
            sys.exit("%s: mean not reproduced (%.1f vs %.1f)" % (name, got, e["mean_us"]))
        if len(ms) > 32:
            sys.exit("%s: %d milestones exceeds FPB_NOTCH_MAX" % (name, len(ms)))
        names.append(name)
        out.append("static const struct fpb_capture_ms fpb_cms_%s[%d] = {" % (name, len(ms)))
        for frac, nm, kind in ms:
            out.append("    { %.9f, %-16s \"%s\" }," % (frac, kind + ",", nm))
        out.append("};")
        knots = ", ".join("%.1f" % v for v in
                          [e[q] for q in KEYS] + [p99, e["max_us"]])
        tbl.append('    { "%s", %d, fpb_cms_%s,\n'
                   "      { %s },\n      %.0f, %u }," %
                   (name, len(ms), name, knots,
                    st["schedule"]["e_total_ns"] / 1000.0, st["profile"]["frames"]))

    blk = [
        BEGIN,
        " * Generated by tools/mkprofile.py from",
        " *   %s" % os.path.basename(path),
        " * %d streams, %d frames of capture. Do not hand-edit; regenerate."
        % (len(streams), sum(s["profile"]["frames"] for _, s in streams)),
        " *",
        " * frac is the milestone's offset as a fraction of that stream's median",
        " * E_total. q_us[] is the E_total inverse CDF at",
        " *   q = 0, .10, .25, .50, .75, .90, .99, 1.0",
        " * The first six are captured. The p99 knot is SOLVED so the sampled mean",
        " * equals the captured mean -- the model's quantiles stop at p90 and give",
        " * the segment above it no shape. max is captured.",
        " */",
        "struct fpb_capture_ms { double frac; uint32_t kind; const char *name; };",
        "struct fpb_capture {",
        "    const char *name;",
        "    uint32_t    n_ms;",
        "    const struct fpb_capture_ms *ms;",
        "    double      q_us[8];",
        "    double      median_us;",
        "    uint32_t    frames;",
        "};",
        "",
    ] + out + [
        "",
        "#define FPB_CAPTURE_COUNT %du" % len(streams),
        "static const struct fpb_capture fpb_captures[FPB_CAPTURE_COUNT] = {",
    ] + tbl + ["};", END]

    src = open(csrc).read()
    i, j = src.index(BEGIN), src.index(END) + len(END)
    open(csrc, "w").write(src[:i] + "\n".join(blk) + src[j:])
    print("spliced %d streams into %s" % (len(streams), csrc))
    for n, (_, st) in zip(names, streams):
        e = st["profile"]["e_total"]
        p99, _ = solve_p99(e)
        print("  %-9s %2d milestones  %5.2f ms median  p99 %5.1f ms  max %5.1f ms  %d frames"
              % (n, len(milestones(st["schedule"])), st["schedule"]["e_total_ns"] / 1e6,
                 p99 / 1000.0, e["max_us"] / 1000.0, st["profile"]["frames"]))


if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    main(sys.argv[1])
